//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw_3_RAD.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection HighscoreListNicks {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["HighscoreListNicks"]));
            }
            set {
                this["HighscoreListNicks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection HighscoreListScore {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["HighscoreListScore"]));
            }
            set {
                this["HighscoreListScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
  <string>#empty</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection HighscoreListDate {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["HighscoreListDate"]));
            }
            set {
                this["HighscoreListDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Buffer {
            get {
                return ((int)(this["Buffer"]));
            }
            set {
                this["Buffer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int Okres {
            get {
                return ((int)(this["Okres"]));
            }
            set {
                this["Okres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ileKlikniec {
            get {
                return ((int)(this["ileKlikniec"]));
            }
            set {
                this["ileKlikniec"] = value;
            }
        }
    }
}
